### ISSUE TITLE
Conda environment

### ISSUE THREAD

**Issue by jaroslawjanas** [ciromattia/kcc#519]
How about adding an `environment.yml` for the poor conda users?
From my testing

```yml
name: kcc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - Pillow>=5.2.0
  - psutil>=5.0.0
  - python-slugify>=1.2.1
  - raven>=6.0.0
  - distro
  - pip
  - pip:
    - mozjpeg-lossless-optimization>=1.1.2
    - PyQt5>=5.6.0
```

seems to work without any issues on my branch on W10.
Can make a PR if I get a green light on this.
